spring:
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/security_jwt
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
application:
  security:
    jwt:
      secret-key: 2F423F4528482B4D6251655468576D5A7134743777217A25432646294A404E63